COMMAND_GET_TIME = '1'
COMMAND_RESET_TIME = '2'
COMMAND_REGISTER = '3'
EIGHT_BITS = 8

# These refer to list indices, not columns in the spreadsheet
CELL_PKEY = 'A1'
COL_PKEY = 0
COL_UID = 1
COL_MEMBER_NAME = 2
COL_MEMBER_TYPE = 3
COL_START_DAY = 4
COL_USES_LASER_A = 8
COL_USES_LASER_B = 9
COL_USES_SHOPBOT = 10
COL_USES_WOOD = 11
COL_USES_METAL = 12
COL_USES_TEXTILE = 13
COL_USES_THREE_D = 14
COL_START_DATA = 'A'
COL_END_DATA = ':O'
