COMMAND_GET_TIME = '1'
COMMAND_RESET_TIME = '2'
COMMAND_REGISTER = '3'
EIGHT_BITS = 8
ERROR = 'ERROR'

# These refer to list indices, not actual columns in the spreadsheet
CELL_PKEY = 'A1'
COL_PKEY = 0
COL_UID = 1
COL_MEMBER_NAME = 2
COL_MEMBER_TYPE = 3
COL_USES_LASER_A = 6
COL_USES_LASER_B = 7
COL_USES_SHOPBOT = 8
COL_USES_WOOD = 9
COL_USES_METAL = 10
COL_USES_TEXTILE = 11
COL_USES_THREE_D = 12
